python test_aime2024.py --local_dir /workspace/data/aime2024
python test_amc.py --local_dir /workspace/data/amc
python test_gaokao.py --local_dir /workspace/data/gaokao
python test_gsm8k.py --local_dir /workspace/data/gsm8k
python test_math500.py --local_dir /workspace/data/math500
python test_minervamath.py --local_dir /workspace/data/minervamath
python test_olympiad.py --local_dir /workspace/data/olympiad
python dapo_math.py --local_dir /workspace/data/dapo_math
python openr1_math_default.py --local_dir /workspace/data/openr1_math
