# Start from the NVIDIA official image (ubuntu-22.04 + cuda-12.6 + python-3.10)
# https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-08.html
FROM verlai/verl:app-verl0.4-sglang0.4.6.post5-vllm0.8.5-mcore0.12.1

# Install verl
RUN git clone https://github.com/volcengine/verl.git && \
    cd verl && \    
    git checkout v0.4.0 && \
    pip install --no-deps -e .

RUN apt-get update && apt-get install -y rsync
RUN apt-get update && apt-get install -y tmux
